Controllers/BudgetController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task_2.Data;
using Task_2.Models;

namespace Task_2.Controllers
{
    public class BudgetController : Controller
    {
        private readonly ApplicationDbContext _context;

        List<GoodsAllocation> goodsAlllo = new List<GoodsAllocation>();
        List<DiasterAllocation> disasterAllo = new List<DiasterAllocation>();
        List<DisasterType> disasterTypes = new List<DisasterType>();
        BudgetAllocation budgets = new BudgetAllocation();
        List<BudgetAllocation> budgetsList; 
        List<double> disasterTypesTotal = new List<double>();
        List<double> goodsTotalAllocation = new List<double>();
        List<double> remainingBudget = new List<double>();

        public BudgetController(ApplicationDbContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {

            budgetsList = new List<BudgetAllocation>();
            disasterAllo = _context.DiasterAllocation.ToList();
            goodsAlllo = _context.GoodsAllocation.ToList();
            disasterTypes = _context.DisasterType.ToList();

            double allotedMoney = 0;
            double allotedGoodsMoney = 0;
            double budgetRemaining = 0;

            for (int x = 0; x <= disasterTypes.Count-1; x++)
            {
                string disaster = disasterTypes[x].disasterType;
                

                for (int y = 0; y <= disasterAllo.Count-1; y++)
                {
                    if (disasterAllo[y].disasterType.Equals(disaster))
                    {
                        allotedMoney += disasterAllo[y].amountAllotted;
                    }
                }
          
                for (int y = 0; y <= goodsAlllo.Count-1; y++)
                {
                    if (goodsAlllo[y].disasterType.Equals(disaster))
                    {
                        allotedGoodsMoney += (goodsAlllo[y].pricePerItem * goodsAlllo[y].quantity);
                    }
                }

                budgets = new BudgetAllocation();
                budgetRemaining = allotedMoney - allotedGoodsMoney;
                budgets.ID = x;
                budgets.disaterType = disaster;
                budgets.disasterBudget = allotedMoney;
                budgets.totalGoodsPurchase = allotedGoodsMoney;
                budgets.budgetRemaining = budgetRemaining;

                budgetsList.Add(budgets);


                
                allotedMoney = 0;
                allotedGoodsMoney = 0;
                budgetRemaining = 0;
                disaster = "";

            }

            return View(budgetsList);
        }
    }
}

Controllers/DisasterTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Task_2.Data;
using Task_2.Models;

namespace Task_2.Controllers
{
    public class DisasterTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DisasterTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DisasterTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.DisasterType.ToListAsync());
        }

        // GET: DisasterTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disasterType = await _context.DisasterType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (disasterType == null)
            {
                return NotFound();
            }

            return View(disasterType);
        }

        // GET: DisasterTypes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: DisasterTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create([Bind("Id,disasterType,startDate,endDate,description,location,aidRequired")] DisasterType DType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(DType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(DType);
        }

        // GET: DisasterTypes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disasterType = await _context.DisasterType.FindAsync(id);
            if (disasterType == null)
            {
                return NotFound();
            }
            return View(disasterType);
        }

        // POST: DisasterTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> Edit(int id, [Bind("Id,disasterType,startDate,endDate,description,location,aidRequired")] DisasterType disasterType_1)
        {
            if (id != disasterType_1.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(disasterType_1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DisasterTypeExists(disasterType_1.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(disasterType_1);
        }

        // GET: DisasterTypes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disasterType = await _context.DisasterType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (disasterType == null)
            {
                return NotFound();
            }

            return View(disasterType);
        }

        // POST: DisasterTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var disasterType = await _context.DisasterType.FindAsync(id);
            _context.DisasterType.Remove(disasterType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DisasterTypeExists(int id)
        {
            return _context.DisasterType.Any(e => e.Id == id);
        }
    }
}

Controllers/GoodsDonationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Task_2.Data;
using Task_2.Models;

namespace Task_2.Controllers
{
    public class GoodsDonationsController : Controller
    {
        private readonly ApplicationDbContext _context;


      

        public GoodsDonationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: GoodsDonations
        public async Task<IActionResult> Index()
        {
          
            return View(await _context.GoodsDonations.ToListAsync());
        }

        // GET: GoodsDonations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goodsDonations = await _context.GoodsDonations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (goodsDonations == null)
            {
                return NotFound();
            }

            return View(goodsDonations);
        }

        // GET: GoodsDonations/Create
        [Authorize]
        public IActionResult Create()
        {
            DisasterType dt = new DisasterType();
            GoodsCategories gc = new GoodsCategories();

            var li = new SelectList(_context.GoodsCategories.OrderBy(l => l.goodsCategory)
                .ToDictionary(us => us.id, us => us.goodsCategory), "Value", "Value");

            var disaster = new SelectList(_context.DisasterType.OrderBy(l => l.disasterType)
               .ToDictionary(us => us.Id, us => us.disasterType), "Value", "Value");


           


            //List<DisasterType> disaster = new List<DisasterType>();
            //List<GoodsCategories> li = new List<GoodsCategories>();



            // li = _context.GoodsCategories.ToList();
            //disaster = _context.DisasterType.ToList();

            ViewBag.listofitems = li;
            ViewBag.disastertypes = disaster;
            return View();
        }

        // POST: GoodsDonations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,itemName,dateReceived,itemNumber,itemType,isAnonymous,disasteType")] GoodsDonations goodsDonations)
        {
            if (ModelState.IsValid)
            {
                _context.Add(goodsDonations);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(goodsDonations);
        }

        // GET: GoodsDonations/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            DisasterType dt = new DisasterType();
            GoodsCategories gc = new GoodsCategories();

            var li = new SelectList(_context.GoodsCategories.OrderBy(l => l.goodsCategory)
                .ToDictionary(us => us.id, us => us.goodsCategory), "Value", "Value");

            var disaster = new SelectList(_context.DisasterType.OrderBy(l => l.disasterType)
               .ToDictionary(us => us.Id, us => us.disasterType), "Value", "Value");

            ViewBag.listofitems = li;
            ViewBag.disastertypes = disaster;

            if (id == null)
            {
                return NotFound();
            }

            var goodsDonations = await _context.GoodsDonations.FindAsync(id);
            if (goodsDonations == null)
            {
                return NotFound();
            }
            return View(goodsDonations);
        }

        // POST: GoodsDonations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,itemName,dateReceived,itemNumber,itemType,isAnonymous,disasteType")] GoodsDonations goodsDonations)
        {
            if (id != goodsDonations.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(goodsDonations);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GoodsDonationsExists(goodsDonations.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(goodsDonations);
        }

        // GET: GoodsDonations/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goodsDonations = await _context.GoodsDonations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (goodsDonations == null)
            {
                return NotFound();
            }

            return View(goodsDonations);
        }

        // POST: GoodsDonations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var goodsDonations = await _context.GoodsDonations.FindAsync(id);
            _context.GoodsDonations.Remove(goodsDonations);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GoodsDonationsExists(int id)
        {
            return _context.GoodsDonations.Any(e => e.Id == id);
        }
    }
}

Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Task_2.Data;
using Task_2.Models;
using System.Dynamic;

namespace Task_2.Controllers
{
    public class ReportsController : Controller
    {
        private readonly ApplicationDbContext _context;
        List<Report> totalMoneyDonations = new List<Report>();
        List<MoneyDonations> moneyDonations = new List<MoneyDonations>();
        List<GoodsDonations> goodsDonations = new List<GoodsDonations>();
        List<ActiveDisasters> activeDisasters = new List<ActiveDisasters>();

        public ReportsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reports
        public async Task<IActionResult> Index()
        {

            moneyDonations = _context.MoneyDonations.ToList();
            goodsDonations = _context.GoodsDonations.ToList();
            activeDisasters = _context.ActiveDisasters.ToList();

          

            Report rep;
            double donation = 0;
            int numGoods = 0;
            for (int x = 0; x <= moneyDonations.Count - 1; x++)
            {

                donation += moneyDonations[x].donationAmount;
            }

            for (int y = 0; y <= goodsDonations.Count - 1; y++)
            {
                numGoods += goodsDonations[y].itemNumber;
            }

            rep = new Report();
            rep.id = 1;
            rep.totalMonetaryDonationsReceived = donation;
            rep.totalNumberOfGoodsReceived = numGoods;
            totalMoneyDonations.Add(rep);

            List<GoodsDonations> gd = new List<GoodsDonations>();
            List<MoneyDonations> md = new List<MoneyDonations>();

            for (int x = 0; x <= activeDisasters.Count - 1; x++)
            {
                string activeD = activeDisasters[x].DisasterType;

                for (int y = 0; y <= goodsDonations.Count - 1; y++)
                {
                    if (goodsDonations[y].disasteType.Equals(activeD))
                    {
                        GoodsDonations gdItem = new GoodsDonations();
                        gdItem = goodsDonations[y];
                        gd.Add(gdItem);
                    }
                }
                for (int z = 0; z <= moneyDonations.Count - 1; z++)
                {
                    if (moneyDonations[z].disasteType.Equals(activeD))
                    {
                        MoneyDonations mdItem = new MoneyDonations();
                        mdItem = moneyDonations[z];
                        md.Add(mdItem);
                    }
                }
            
            }


            dynamic mymodal = new ExpandoObject();
            mymodal.Report = totalMoneyDonations;
            mymodal.MoneyDonations = md;
            mymodal.GoodsDonations = gd;

            return View(mymodal);
        }

       
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task_2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MoneyDonations" asp-action="Index">Money Donations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GoodsDonations" asp-action="Index">Goods Donations</a>
                        </li>
                      

                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            

            </div>
        </nav>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="DiasterAllocations" asp-action="Index">Money Allocation</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="GoodsAllocations" asp-action="Index">Goods Allocation</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Budget" asp-action="Index">Budget</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="DisasterTypes" asp-action="Index">Add Disaster</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="GoodsCategories" asp-action="Index">Add Goods Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ActiveDisasters" asp-action="Index">Active Disaters</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Report</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Task_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>